### ISSUE TITLE
Review extensions for use in SPNHC for material core

### ISSUE THREAD

**Issue by timrobertson100** [gbif/rs.gbif.org#110]
For extensions we wish to install in the test IPT3 for the SPNHC workshop we need to ensure they are suitable for the Material Core in sandbox. 

All the [DwC extensions](https://rs.gbif.org/extension/dwc/) will need to reference the Material core if they are to be used for example. To do that, we issue a new edition in the sandbox (new file name with date etc) and update and install them in the IPT.

Given the timeline, and questions about our hack(!) we should omit Occurrence as an extension to Material. It needs to come, but we won't have time to make that robust. I propose we focus the excercise more on measurements, identification history, media, relationships, identifiers, chronometric age etc.

**Comment by ManonGros** [comment]
I think we will need at least the **[Resource Relationship](https://rs.gbif.org/extension/dwc/resource_relationship_2022-02-02.xml)** extension and the [Audubon Media Description](https://rs.gbif.org/extension/ac/audubon_2020_10_06.xml) extension because that will be needed for mapping our example dataset.

In addition to that, we want participants to bring their data and they will likely need more extensions. I think the following extensions could be useful for the Natural History Museum crowd:
* [DNA derived data](https://rs.gbif.org/extension/gbif/1.0/dna_derived_data_2022-02-23.xml)
* [Simple Multimedia](https://rs.gbif.org/extension/gbif/1.0/multimedia.xml)
* [GGBN Preparation Extension](https://rs.gbif.org/extension/ggbn/preparation.xml)
* [GGBN Preservation Extension](https://rs.gbif.org/extension/ggbn/preservation.xml)
* [GGBN Loan Extension](https://rs.gbif.org/extension/ggbn/loan.xml)
* [GGBN Permit Extension](https://rs.gbif.org/extension/ggbn/permit_2022-08-08.xml)
* [Identification History](https://rs.gbif.org/extension/dwc/identification_history_2022-02-02.xml)
* [Literature References](https://rs.gbif.org/extension/gbif/1.0/references.xml)
* [Types and Specimen](https://rs.gbif.org/extension/gbif/1.0/typesandspecimen.xml)
* [Alternative Identifiers](https://rs.gbif.org/extension/gbif/1.0/identifier.xml)

I am pretty sure most of the ones above won't be used but just in case, they might be good to have.

**Comment by timrobertson100** [comment]
Thanks for the list @ManonGros 

For SPNCH @mike-podolskiy90 prefers just to let the IPT admins enable any extension that is suitable for Occurrence to be available for Material core. We would need to do what is outlined in this if moving to production though.

I'll close this issue - please reopen this and comment if you spot any issues with the planned approach.
