### ISSUE TITLE
Reestablish the SANDBOX Plinian Core extensions

### ISSUE THREAD

**Issue by timrobertson100** [gbif/rs.gbif.org#67]
The [original extensions](https://github.com/gbif/rs.gbif.org/blob/master/sandbox/extension/external.json) are seemingly offline.

We should re-enable these to support the work of the TDWG group aiming to revise Plinian Core and seek ratification.

**Comment by WUlate** [comment]
Got it, thanks! Sorry, I was looking in the wrong place.  Agree, best to keep'em together, I got confused because I was looking at the other extensions there.

When are extensions moved out of the sandbox? Do you mean TDWG's SDS-compliant (ratified) Standard or is this a differetn ratification process?

**Comment by timrobertson100** [comment]
That’s @WUlate 

Things that are on a standards track in TDWG would go with the TDWG ratification. 

There have been some more bespoke extensions back in the day, which served a community need but all the recent ones (DNA, Audubon etc) went through the TDWG standard or task group review.

Here I’d suggest doing it properly as part of the TDWG standard.

Would that suit your work? If not, we can rethink accordingly.
